[project]
name = "nftcontract"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.acat-nft]
path = "contracts/acat-nft.clar"
depends_on = ["sip009-nft-trait"]

[contracts.acat-v2-nft]
path = "contracts/acat-v2-nft.clar"
depends_on = ["sip009-nft-trait"]

[contracts.acatv4]
path = "contracts/acatv4.clar"
depends_on = ["sip009-nft-trait"]

[contracts.maps]
path = "contracts/maps.clar"
depends_on = []

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
